return function()
  require'keymappings.buffers'()
  require'keymappings.command-line'()
  require'keymappings.insert'()
  require'keymappings.lsp'()
  require'keymappings.navigation'()
  require'keymappings.remaps'()
  require'keymappings.search'()
  require'keymappings.substitute'()
  require'keymappings.tabs'()
  require'keymappings.text'()
  require'keymappings.vim'()
  require'keymappings.visual'()
  require'keymappings.windows'()
end
