return function(opts)
  require'plugin-keymappings.telescope.buffers'()
  require'plugin-keymappings.telescope.find_files'()
  require'plugin-keymappings.telescope.find_within_buffer'(opts)
  require'plugin-keymappings.telescope.git'()
  require'plugin-keymappings.telescope.history'()
  require'plugin-keymappings.telescope.lsp'(opts)
  require'plugin-keymappings.telescope.resume'()
  require'plugin-keymappings.telescope.vim'()
end
