return function (opts)
  require'plugin-settings.airline'(opts)
  require'plugin-settings.cmp'(opts)
  require'plugin-settings.easymotion'(opts)
  require'plugin-settings.elixir-nvim'(opts)
  require'plugin-settings.gundo'()
  require'plugin-settings.nerdcommenter'()
  require'plugin-settings.nvim-treesitter'()
  require'plugin-settings.slime'()
  require'plugin-settings.telescope'()
end
