return function()
  require'plugin-keymappings.easyalign'()
  require'plugin-keymappings.easymotion'()
  require'plugin-keymappings.gundo'()
  require'plugin-keymappings.lsp'()
  require'plugin-keymappings.miniyank'()
  require'plugin-keymappings.nerdcommenter'()
  require'plugin-keymappings.nerdtree'()
  require'plugin-keymappings.slime'()
  require'plugin-keymappings.telescope'()
end
