return function(opts)
  require'plugin-keymappings.coc'(opts)
  require'plugin-keymappings.easyalign'()
  require'plugin-keymappings.easymotion'(opts)
  require'plugin-keymappings.gundo'()
  require'plugin-keymappings.lsp'(opts)
  require'plugin-keymappings.miniyank'()
  require'plugin-keymappings.nerdcommenter'()
  require'plugin-keymappings.nerdtree'()
  require'plugin-keymappings.slime'()
  require'plugin-keymappings.telescope'(opts)
end
