return function()
  require'keymappings.normal.buffers'()
  require'keymappings.normal.navigation'()
  require'keymappings.normal.remaps'()
  require'keymappings.normal.search'()
  require'keymappings.normal.substitute'()
  require'keymappings.normal.tabs'()
  require'keymappings.normal.text'()
  require'keymappings.normal.vim'()
  require'keymappings.normal.visual'()
  require'keymappings.normal.windows'()
end
