return function (opts)
  require'plugins.settings.airline'(opts)
  require'plugins.settings.cmp'(opts)
  require'plugins.settings.easymotion'(opts)
  require'plugins.settings.gundo'()
  require'plugins.settings.nerdcommenter'()
  require'plugins.settings.treesitter'()
  require'plugins.settings.slime'()
  require'plugins.settings.telescope'()
  require'plugins.settings.which-key'(opts)
end
